version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      #start_period: 60s

  kibana1:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es1:9200
      ELASTICSEARCH_HOSTS: http://es1:9200
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]
      retries: 10

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash1
    environment:
      - ES_JAVA_OPTS='-Xms1g -Xmx1g'
    volumes:
      - logstashp:/usr/share/logstash/pipeline/
      - logstashc:/usr/share/logstash/config/
    ports:
      - 5000:5000
      - 5044-5044
    networks:
      - elastic
    restart: on-failure

  pktb01:
    image: docker.elastic.co/beats/data:7.6.2
    container_name: pktb1
    user: data
    volumes:
      - ./data:/usr/share/packetbeat/data
      - ./conf/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: host
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
    command: >
      packetbeat
         -e
         -strict.perms=false
         -E setup.kibana.host="localhost:5601"
         -E setup.dashboards.enabled=true
    restart: on-failure
    depends_on:
      es01:
        condition: service_healthy
      kibana1:
        condition: service_healthy

volumes:
  data_es1:
    driver: local
  logstashp:
    driver: local
  logstashc:
    driver: local

networks:
  elastic:
    driver: bridge